# Generated by Django 4.1.4 on 2023-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
