# Generated by Django 4.1.4 on 2023-08-01 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_deletedtodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedtodo',
            old_name='deletion_date',
            new_name='deleted_at',
        ),
        migrations.AlterField(
            model_name='deletedtodo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
